// Generated by scripts/generate-data.mjs from flag-atlas-data-assets.zip.
// Do not edit manually — see docs/attribution/ for source and attribution.
// Bandeiras extras (territórios e afins) fora do MVP, preservadas para expansão futura.
import type { ExtraFlag } from "@/entities/country/country.types";

export const EXTRA_FLAGS: readonly ExtraFlag[] = [
  {
    id: "ai",
    nameEn: "Anguilla",
    flagPath: "flags/extras/ai.svg",
  },
  {
    id: "aq",
    nameEn: "Antarctica",
    flagPath: "flags/extras/aq.svg",
  },
  {
    id: "as",
    nameEn: "American Samoa",
    flagPath: "flags/extras/as.svg",
  },
  {
    id: "aw",
    nameEn: "Aruba",
    flagPath: "flags/extras/aw.svg",
  },
  {
    id: "ax",
    nameEn: "Åland Islands",
    flagPath: "flags/extras/ax.svg",
  },
  {
    id: "bl",
    nameEn: "Saint Barthélemy",
    flagPath: "flags/extras/bl.svg",
  },
  {
    id: "bm",
    nameEn: "Bermuda",
    flagPath: "flags/extras/bm.svg",
  },
  {
    id: "bq",
    nameEn: "Bonaire, Sint Eustatius and Saba",
    flagPath: "flags/extras/bq.svg",
  },
  {
    id: "bv",
    nameEn: "Bouvet Island",
    flagPath: "flags/extras/bv.svg",
  },
  {
    id: "cc",
    nameEn: "Cocos (Keeling) Islands",
    flagPath: "flags/extras/cc.svg",
  },
  {
    id: "ck",
    nameEn: "Cook Islands",
    flagPath: "flags/extras/ck.svg",
  },
  {
    id: "cw",
    nameEn: "Curaçao",
    flagPath: "flags/extras/cw.svg",
  },
  {
    id: "cx",
    nameEn: "Christmas Island",
    flagPath: "flags/extras/cx.svg",
  },
  {
    id: "eh",
    nameEn: "Western Sahara",
    flagPath: "flags/extras/eh.svg",
  },
  {
    id: "fk",
    nameEn: "Falkland Islands (Malvinas)",
    flagPath: "flags/extras/fk.svg",
  },
  {
    id: "fo",
    nameEn: "Faroe Islands",
    flagPath: "flags/extras/fo.svg",
  },
  {
    id: "gb-eng",
    nameEn: "England",
    flagPath: "flags/extras/gb-eng.svg",
  },
  {
    id: "gb-nir",
    nameEn: "Northern Ireland",
    flagPath: "flags/extras/gb-nir.svg",
  },
  {
    id: "gb-sct",
    nameEn: "Scotland",
    flagPath: "flags/extras/gb-sct.svg",
  },
  {
    id: "gb-wls",
    nameEn: "Wales",
    flagPath: "flags/extras/gb-wls.svg",
  },
  {
    id: "gf",
    nameEn: "French Guiana",
    flagPath: "flags/extras/gf.svg",
  },
  {
    id: "gg",
    nameEn: "Guernsey",
    flagPath: "flags/extras/gg.svg",
  },
  {
    id: "gi",
    nameEn: "Gibraltar",
    flagPath: "flags/extras/gi.svg",
  },
  {
    id: "gl",
    nameEn: "Greenland",
    flagPath: "flags/extras/gl.svg",
  },
  {
    id: "gp",
    nameEn: "Guadeloupe",
    flagPath: "flags/extras/gp.svg",
  },
  {
    id: "gs",
    nameEn: "South Georgia and the South Sandwich Islands",
    flagPath: "flags/extras/gs.svg",
  },
  {
    id: "gu",
    nameEn: "Guam",
    flagPath: "flags/extras/gu.svg",
  },
  {
    id: "hk",
    nameEn: "Hong Kong",
    flagPath: "flags/extras/hk.svg",
  },
  {
    id: "hm",
    nameEn: "Heard Island and McDonald Islands",
    flagPath: "flags/extras/hm.svg",
  },
  {
    id: "im",
    nameEn: "Isle of Man",
    flagPath: "flags/extras/im.svg",
  },
  {
    id: "io",
    nameEn: "British Indian Ocean Territory",
    flagPath: "flags/extras/io.svg",
  },
  {
    id: "je",
    nameEn: "Jersey",
    flagPath: "flags/extras/je.svg",
  },
  {
    id: "ky",
    nameEn: "Cayman Islands",
    flagPath: "flags/extras/ky.svg",
  },
  {
    id: "mf",
    nameEn: "Saint Martin (French part)",
    flagPath: "flags/extras/mf.svg",
  },
  {
    id: "mo",
    nameEn: "Macao",
    flagPath: "flags/extras/mo.svg",
  },
  {
    id: "mp",
    nameEn: "Northern Mariana Islands",
    flagPath: "flags/extras/mp.svg",
  },
  {
    id: "mq",
    nameEn: "Martinique",
    flagPath: "flags/extras/mq.svg",
  },
  {
    id: "ms",
    nameEn: "Montserrat",
    flagPath: "flags/extras/ms.svg",
  },
  {
    id: "nc",
    nameEn: "New Caledonia",
    flagPath: "flags/extras/nc.svg",
  },
  {
    id: "nf",
    nameEn: "Norfolk Island",
    flagPath: "flags/extras/nf.svg",
  },
  {
    id: "nu",
    nameEn: "Niue",
    flagPath: "flags/extras/nu.svg",
  },
  {
    id: "pf",
    nameEn: "French Polynesia",
    flagPath: "flags/extras/pf.svg",
  },
  {
    id: "pm",
    nameEn: "Saint Pierre and Miquelon",
    flagPath: "flags/extras/pm.svg",
  },
  {
    id: "pn",
    nameEn: "Pitcairn",
    flagPath: "flags/extras/pn.svg",
  },
  {
    id: "pr",
    nameEn: "Puerto Rico",
    flagPath: "flags/extras/pr.svg",
  },
  {
    id: "re",
    nameEn: "Réunion",
    flagPath: "flags/extras/re.svg",
  },
  {
    id: "sh",
    nameEn: "Saint Helena, Ascension and Tristan da Cunha",
    flagPath: "flags/extras/sh.svg",
  },
  {
    id: "sj",
    nameEn: "Svalbard and Jan Mayen",
    flagPath: "flags/extras/sj.svg",
  },
  {
    id: "sx",
    nameEn: "Sint Maarten (Dutch part)",
    flagPath: "flags/extras/sx.svg",
  },
  {
    id: "tc",
    nameEn: "Turks and Caicos Islands",
    flagPath: "flags/extras/tc.svg",
  },
  {
    id: "tf",
    nameEn: "French Southern Territories",
    flagPath: "flags/extras/tf.svg",
  },
  {
    id: "tk",
    nameEn: "Tokelau",
    flagPath: "flags/extras/tk.svg",
  },
  {
    id: "tw",
    nameEn: "Taiwan, Province of China",
    flagPath: "flags/extras/tw.svg",
  },
  {
    id: "um",
    nameEn: "United States Minor Outlying Islands",
    flagPath: "flags/extras/um.svg",
  },
  {
    id: "vg",
    nameEn: "Virgin Islands, British",
    flagPath: "flags/extras/vg.svg",
  },
  {
    id: "vi",
    nameEn: "Virgin Islands, U.S.",
    flagPath: "flags/extras/vi.svg",
  },
  {
    id: "wf",
    nameEn: "Wallis and Futuna",
    flagPath: "flags/extras/wf.svg",
  },
  {
    id: "xk",
    nameEn: "Kosovo",
    flagPath: "flags/extras/xk.svg",
  },
  {
    id: "yt",
    nameEn: "Mayotte",
    flagPath: "flags/extras/yt.svg",
  },
];
