import type { CosmeticItem } from "./cosmetic.types";

/**
 * Catálogo de cosméticos da Versão 4. É código, não storage: só o inventário
 * do jogador (moedas, itens comprados e equipados) é persistido.
 *
 * Convenções:
 * - ids são estáveis e prefixados pelo tipo (theme-, sound-, frame-, ...);
 * - itens com price 0 são gratuitos e sempre possuídos;
 * - itens isDefault são o padrão equipado do seu tipo e nunca podem ser vendidos.
 */

const THEMES: readonly CosmeticItem[] = [
  {
    id: "theme-default",
    type: "theme",
    nameKey: "cosmetics.items.theme-default.name",
    descriptionKey: "cosmetics.items.theme-default.description",
    price: 0,
    rarity: "common",
    icon: "globe-half",
    isDefault: true,
  },
  {
    id: "theme-mapa-antigo",
    type: "theme",
    nameKey: "cosmetics.items.theme-mapa-antigo.name",
    descriptionKey: "cosmetics.items.theme-mapa-antigo.description",
    price: 120,
    rarity: "rare",
    icon: "map",
  },
  {
    id: "theme-neon",
    type: "theme",
    nameKey: "cosmetics.items.theme-neon.name",
    descriptionKey: "cosmetics.items.theme-neon.description",
    price: 150,
    rarity: "epic",
    icon: "zap",
  },
  {
    id: "theme-oceano",
    type: "theme",
    nameKey: "cosmetics.items.theme-oceano.name",
    descriptionKey: "cosmetics.items.theme-oceano.description",
    price: 120,
    rarity: "rare",
    icon: "waves",
  },
  {
    id: "theme-espaco",
    type: "theme",
    nameKey: "cosmetics.items.theme-espaco.name",
    descriptionKey: "cosmetics.items.theme-espaco.description",
    price: 150,
    rarity: "epic",
    icon: "planet",
  },
  {
    id: "theme-biblioteca",
    type: "theme",
    nameKey: "cosmetics.items.theme-biblioteca.name",
    descriptionKey: "cosmetics.items.theme-biblioteca.description",
    price: 120,
    rarity: "rare",
    icon: "book",
  },
  {
    id: "theme-minimalista",
    type: "theme",
    nameKey: "cosmetics.items.theme-minimalista.name",
    descriptionKey: "cosmetics.items.theme-minimalista.description",
    price: 100,
    rarity: "common",
    icon: "minimal",
  },
  {
    id: "theme-flaggo-light",
    type: "theme",
    nameKey: "cosmetics.items.theme-flaggo-light.name",
    descriptionKey: "cosmetics.items.theme-flaggo-light.description",
    price: 60,
    rarity: "common",
    icon: "sparkles",
  },
  {
    id: "theme-flaggo-night",
    type: "theme",
    nameKey: "cosmetics.items.theme-flaggo-night.name",
    descriptionKey: "cosmetics.items.theme-flaggo-night.description",
    price: 60,
    rarity: "common",
    icon: "star",
  },
];

const SOUND_PACKS: readonly CosmeticItem[] = [
  {
    id: "sound-default",
    type: "soundPack",
    nameKey: "cosmetics.items.sound-default.name",
    descriptionKey: "cosmetics.items.sound-default.description",
    price: 0,
    rarity: "common",
    icon: "volume",
    isDefault: true,
  },
  {
    id: "sound-silent",
    type: "soundPack",
    nameKey: "cosmetics.items.sound-silent.name",
    descriptionKey: "cosmetics.items.sound-silent.description",
    price: 0,
    rarity: "common",
    icon: "volume-off",
  },
  {
    id: "sound-suave",
    type: "soundPack",
    nameKey: "cosmetics.items.sound-suave.name",
    descriptionKey: "cosmetics.items.sound-suave.description",
    price: 80,
    rarity: "common",
    icon: "music",
  },
  {
    id: "sound-arcade",
    type: "soundPack",
    nameKey: "cosmetics.items.sound-arcade.name",
    descriptionKey: "cosmetics.items.sound-arcade.description",
    price: 110,
    rarity: "rare",
    icon: "gamepad",
  },
  {
    id: "sound-digital",
    type: "soundPack",
    nameKey: "cosmetics.items.sound-digital.name",
    descriptionKey: "cosmetics.items.sound-digital.description",
    price: 110,
    rarity: "rare",
    icon: "waveform",
  },
];

const FLAG_FRAMES: readonly CosmeticItem[] = [
  {
    id: "frame-default",
    type: "flagFrame",
    nameKey: "cosmetics.items.frame-default.name",
    descriptionKey: "cosmetics.items.frame-default.description",
    price: 0,
    rarity: "common",
    icon: "square",
    isDefault: true,
  },
  {
    id: "frame-atlas",
    type: "flagFrame",
    nameKey: "cosmetics.items.frame-atlas.name",
    descriptionKey: "cosmetics.items.frame-atlas.description",
    price: 90,
    rarity: "common",
    icon: "compass",
  },
  {
    id: "frame-madeira",
    type: "flagFrame",
    nameKey: "cosmetics.items.frame-madeira.name",
    descriptionKey: "cosmetics.items.frame-madeira.description",
    price: 110,
    rarity: "rare",
    icon: "leaf",
  },
  {
    id: "frame-neon",
    type: "flagFrame",
    nameKey: "cosmetics.items.frame-neon.name",
    descriptionKey: "cosmetics.items.frame-neon.description",
    price: 140,
    rarity: "epic",
    icon: "zap",
  },
  {
    id: "frame-oceano",
    type: "flagFrame",
    nameKey: "cosmetics.items.frame-oceano.name",
    descriptionKey: "cosmetics.items.frame-oceano.description",
    price: 110,
    rarity: "rare",
    icon: "waves",
  },
  {
    id: "frame-biblioteca",
    type: "flagFrame",
    nameKey: "cosmetics.items.frame-biblioteca.name",
    descriptionKey: "cosmetics.items.frame-biblioteca.description",
    price: 110,
    rarity: "rare",
    icon: "book",
  },
  {
    id: "frame-turquesa",
    type: "flagFrame",
    nameKey: "cosmetics.items.frame-turquesa.name",
    descriptionKey: "cosmetics.items.frame-turquesa.description",
    price: 120,
    rarity: "common",
    icon: "waves",
  },
  {
    id: "frame-coral",
    type: "flagFrame",
    nameKey: "cosmetics.items.frame-coral.name",
    descriptionKey: "cosmetics.items.frame-coral.description",
    price: 120,
    rarity: "common",
    icon: "heart",
  },
  {
    id: "frame-minimal",
    type: "flagFrame",
    nameKey: "cosmetics.items.frame-minimal.name",
    descriptionKey: "cosmetics.items.frame-minimal.description",
    price: 90,
    rarity: "common",
    icon: "minimal",
  },
  {
    id: "frame-aurora",
    type: "flagFrame",
    nameKey: "cosmetics.items.frame-aurora.name",
    descriptionKey: "cosmetics.items.frame-aurora.description",
    price: 180,
    rarity: "rare",
    icon: "sparkles",
  },
  {
    id: "frame-ouro",
    type: "flagFrame",
    nameKey: "cosmetics.items.frame-ouro.name",
    descriptionKey: "cosmetics.items.frame-ouro.description",
    price: 220,
    rarity: "epic",
    icon: "crown",
  },
  {
    id: "frame-festivo",
    type: "flagFrame",
    nameKey: "cosmetics.items.frame-festivo.name",
    descriptionKey: "cosmetics.items.frame-festivo.description",
    price: 160,
    rarity: "seasonal",
    icon: "party",
  },
];

const ORBI_COSMETICS: readonly CosmeticItem[] = [
  {
    id: "orbi-classic",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-classic.name",
    descriptionKey: "cosmetics.items.orbi-classic.description",
    price: 0,
    rarity: "common",
    icon: "globe",
    isDefault: true,
  },
  {
    id: "orbi-explorer-hat",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-explorer-hat.name",
    descriptionKey: "cosmetics.items.orbi-explorer-hat.description",
    price: 240,
    rarity: "epic",
    icon: "compass",
  },
  {
    id: "orbi-cap",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-cap.name",
    descriptionKey: "cosmetics.items.orbi-cap.description",
    price: 120,
    rarity: "common",
    icon: "shield",
  },
  {
    id: "orbi-beanie",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-beanie.name",
    descriptionKey: "cosmetics.items.orbi-beanie.description",
    price: 120,
    rarity: "common",
    icon: "snowflake",
  },
  {
    id: "orbi-party-hat",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-party-hat.name",
    descriptionKey: "cosmetics.items.orbi-party-hat.description",
    price: 160,
    rarity: "rare",
    icon: "party",
  },
  {
    id: "orbi-crown",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-crown.name",
    descriptionKey: "cosmetics.items.orbi-crown.description",
    price: 320,
    rarity: "legendary",
    icon: "crown",
  },
  {
    id: "orbi-halo",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-halo.name",
    descriptionKey: "cosmetics.items.orbi-halo.description",
    price: 200,
    rarity: "epic",
    icon: "sparkles",
  },
  {
    id: "orbi-glasses",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-glasses.name",
    descriptionKey: "cosmetics.items.orbi-glasses.description",
    price: 100,
    rarity: "common",
    icon: "search",
  },
  {
    id: "orbi-sunglasses",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-sunglasses.name",
    descriptionKey: "cosmetics.items.orbi-sunglasses.description",
    price: 140,
    rarity: "rare",
    icon: "zap",
  },
  {
    id: "orbi-monocle",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-monocle.name",
    descriptionKey: "cosmetics.items.orbi-monocle.description",
    price: 180,
    rarity: "rare",
    icon: "search",
  },
  {
    id: "orbi-scarf",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-scarf.name",
    descriptionKey: "cosmetics.items.orbi-scarf.description",
    price: 130,
    rarity: "common",
    icon: "waves",
  },
  {
    id: "orbi-bowtie",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-bowtie.name",
    descriptionKey: "cosmetics.items.orbi-bowtie.description",
    price: 110,
    rarity: "common",
    icon: "gem",
  },
  {
    id: "orbi-headphones",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-headphones.name",
    descriptionKey: "cosmetics.items.orbi-headphones.description",
    price: 170,
    rarity: "rare",
    icon: "music",
  },
  {
    id: "orbi-winter",
    type: "orbiCosmetic",
    nameKey: "cosmetics.items.orbi-winter.name",
    descriptionKey: "cosmetics.items.orbi-winter.description",
    price: 220,
    rarity: "seasonal",
    icon: "snowflake",
  },
];

const AVATAR_COSMETICS: readonly CosmeticItem[] = [
  {
    id: "avatar-explorer",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-explorer.name",
    descriptionKey: "cosmetics.items.avatar-explorer.description",
    price: 0,
    rarity: "common",
    icon: "user",
    isDefault: true,
  },
  {
    id: "avatar-ocean",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-ocean.name",
    descriptionKey: "cosmetics.items.avatar-ocean.description",
    price: 90,
    rarity: "common",
    icon: "waves",
  },
  {
    id: "avatar-forest",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-forest.name",
    descriptionKey: "cosmetics.items.avatar-forest.description",
    price: 90,
    rarity: "common",
    icon: "leaf",
  },
  {
    id: "avatar-sand",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-sand.name",
    descriptionKey: "cosmetics.items.avatar-sand.description",
    price: 90,
    rarity: "common",
    icon: "map",
  },
  {
    id: "avatar-mint",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-mint.name",
    descriptionKey: "cosmetics.items.avatar-mint.description",
    price: 100,
    rarity: "common",
    icon: "sprout",
  },
  {
    id: "avatar-slate",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-slate.name",
    descriptionKey: "cosmetics.items.avatar-slate.description",
    price: 100,
    rarity: "common",
    icon: "minimal",
  },
  {
    id: "avatar-sunset",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-sunset.name",
    descriptionKey: "cosmetics.items.avatar-sunset.description",
    price: 110,
    rarity: "common",
    icon: "zap",
  },
  {
    id: "avatar-lagoon",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-lagoon.name",
    descriptionKey: "cosmetics.items.avatar-lagoon.description",
    price: 110,
    rarity: "common",
    icon: "waves",
  },
  {
    id: "avatar-rose",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-rose.name",
    descriptionKey: "cosmetics.items.avatar-rose.description",
    price: 120,
    rarity: "common",
    icon: "heart",
  },
  {
    id: "avatar-berry",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-berry.name",
    descriptionKey: "cosmetics.items.avatar-berry.description",
    price: 120,
    rarity: "rare",
    icon: "gem",
  },
  {
    id: "avatar-midnight",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-midnight.name",
    descriptionKey: "cosmetics.items.avatar-midnight.description",
    price: 140,
    rarity: "rare",
    icon: "star",
  },
  {
    id: "avatar-ember",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-ember.name",
    descriptionKey: "cosmetics.items.avatar-ember.description",
    price: 140,
    rarity: "rare",
    icon: "flame",
  },
  {
    id: "avatar-aurora",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-aurora.name",
    descriptionKey: "cosmetics.items.avatar-aurora.description",
    price: 160,
    rarity: "rare",
    icon: "sparkles",
  },
  {
    id: "avatar-royal",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-royal.name",
    descriptionKey: "cosmetics.items.avatar-royal.description",
    price: 160,
    rarity: "rare",
    icon: "crown",
  },
  {
    id: "avatar-gold",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-gold.name",
    descriptionKey: "cosmetics.items.avatar-gold.description",
    price: 260,
    rarity: "epic",
    icon: "medal",
  },
  {
    id: "avatar-nebula",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-nebula.name",
    descriptionKey: "cosmetics.items.avatar-nebula.description",
    price: 280,
    rarity: "epic",
    icon: "planet",
  },
  {
    id: "avatar-prism",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-prism.name",
    descriptionKey: "cosmetics.items.avatar-prism.description",
    price: 340,
    rarity: "legendary",
    icon: "gems",
  },
  {
    id: "avatar-carnival",
    type: "avatarCosmetic",
    nameKey: "cosmetics.items.avatar-carnival.name",
    descriptionKey: "cosmetics.items.avatar-carnival.description",
    price: 200,
    rarity: "seasonal",
    icon: "party",
  },
];

const VISUAL_EFFECTS: readonly CosmeticItem[] = [
  {
    id: "effect-none",
    type: "visualEffect",
    nameKey: "cosmetics.items.effect-none.name",
    descriptionKey: "cosmetics.items.effect-none.description",
    price: 0,
    rarity: "common",
    icon: "ban",
    isDefault: true,
  },
  {
    id: "effect-glow",
    type: "visualEffect",
    nameKey: "cosmetics.items.effect-glow.name",
    descriptionKey: "cosmetics.items.effect-glow.description",
    price: 90,
    rarity: "common",
    icon: "sparkles",
  },
  {
    id: "effect-confetti",
    type: "visualEffect",
    nameKey: "cosmetics.items.effect-confetti.name",
    descriptionKey: "cosmetics.items.effect-confetti.description",
    price: 130,
    rarity: "rare",
    icon: "party",
  },
  {
    id: "effect-neon-pulse",
    type: "visualEffect",
    nameKey: "cosmetics.items.effect-neon-pulse.name",
    descriptionKey: "cosmetics.items.effect-neon-pulse.description",
    price: 130,
    rarity: "rare",
    icon: "activity",
  },
  {
    id: "effect-stars",
    type: "visualEffect",
    nameKey: "cosmetics.items.effect-stars.name",
    descriptionKey: "cosmetics.items.effect-stars.description",
    price: 110,
    rarity: "common",
    icon: "star",
  },
];

export const COSMETIC_CATALOG: readonly CosmeticItem[] = [
  ...THEMES,
  ...SOUND_PACKS,
  ...FLAG_FRAMES,
  ...VISUAL_EFFECTS,
  ...ORBI_COSMETICS,
  ...AVATAR_COSMETICS,
];
