/**
 * Gera src/shared/data/{countries,continents,extras}.ts a partir do pacote
 * oficial de dados extraído de `_inputs/flag-atlas-data-assets.zip`.
 *
 * Uso:
 *   node scripts/generate-data.mjs <caminho-do-zip-extraido>
 *
 * O diretório informado deve conter `src/data/countries.json`,
 * `src/data/continents.json` e `src/data/extras.json`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const sourceDir = process.argv[2];

if (!sourceDir) {
  console.error("Usage: node scripts/generate-data.mjs <extracted-data-assets-dir>");
  process.exit(1);
}

const dataDir = resolve(sourceDir, "src", "data");
const outDir = resolve(import.meta.dirname, "..", "src", "shared", "data");

const countries = JSON.parse(readFileSync(join(dataDir, "countries.json"), "utf8"));
const continents = JSON.parse(readFileSync(join(dataDir, "continents.json"), "utf8"));
const extras = JSON.parse(readFileSync(join(dataDir, "extras.json"), "utf8"));

/**
 * Nomes públicos amigáveis exigidos por .specs/DATA_AND_ASSETS.md §6.
 * Os nomes formais/alternativos são preservados como aliases para o
 * futuro modo digitação.
 */
const overrides = {
  va: {
    names: { "pt-BR": "Vaticano" },
    aliases: {
      "pt-BR": ["Santa Sé", "Vaticano ou Santa Sé", "Cidade do Vaticano"],
      "en-US": ["Holy See", "Vatican"],
    },
  },
  cz: {
    names: { "pt-BR": "República Tcheca" },
    aliases: { "pt-BR": ["Tchéquia"], "en-US": ["Czech Republic"] },
  },
  tr: {
    names: { "en-US": "Turkey" },
    aliases: { "en-US": ["Türkiye"] },
  },
  us: {
    aliases: {
      "pt-BR": ["EUA", "Estados Unidos da América"],
      "en-US": ["USA", "United States of America"],
    },
  },
  gb: {
    aliases: { "pt-BR": ["Grã-Bretanha"], "en-US": ["UK", "Great Britain"] },
  },
  ci: {
    aliases: { "en-US": ["Ivory Coast"] },
  },
  sz: {
    aliases: { "pt-BR": ["Suazilândia"], "en-US": ["Swaziland"] },
  },
  mm: {
    aliases: { "pt-BR": ["Birmânia"], "en-US": ["Burma"] },
  },
};

function toCountry(raw) {
  const override = overrides[raw.id] ?? {};
  const country = {
    id: raw.id,
    iso2: raw.iso2,
    names: {
      "pt-BR": override.names?.["pt-BR"] ?? raw.name.ptBR,
      "en-US": override.names?.["en-US"] ?? raw.name.en,
    },
    continentId: raw.continentId,
    flagPath: raw.flag.replace(/^\//, ""),
    slug: raw.slug,
  };
  if (override.aliases) {
    country.aliases = override.aliases;
  }
  return country;
}

function toContinent(raw) {
  return {
    id: raw.id,
    names: { "pt-BR": raw.name.ptBR, "en-US": raw.name.en },
    emoji: raw.emoji,
    order: raw.order,
    countryIds: raw.countryIds,
  };
}

/** Nomes ausentes no pacote original para alguns extras conhecidos. */
const extraNameFallbacks = {
  "gb-eng": "England",
  "gb-nir": "Northern Ireland",
  "gb-sct": "Scotland",
  "gb-wls": "Wales",
  xk: "Kosovo",
};

function toExtraFlag(raw) {
  const nameEn = raw.name ?? extraNameFallbacks[raw.id];
  if (!nameEn) {
    throw new Error(`Extra flag "${raw.id}" has no name and no fallback`);
  }
  return {
    id: raw.id,
    nameEn,
    flagPath: raw.flag.replace(/^\//, ""),
  };
}

const header = `// Generated by scripts/generate-data.mjs from flag-atlas-data-assets.zip.
// Do not edit manually — see docs/attribution/ for source and attribution.`;

writeFileSync(
  join(outDir, "countries.ts"),
  `${header}
import type { Country } from "@/entities/country/country.types";

export const COUNTRIES: readonly Country[] = ${JSON.stringify(countries.map(toCountry), null, 2)};
`,
);

writeFileSync(
  join(outDir, "continents.ts"),
  `${header}
import type { Continent } from "@/entities/continent/continent.types";

export const CONTINENTS: readonly Continent[] = ${JSON.stringify(continents.map(toContinent), null, 2)};
`,
);

writeFileSync(
  join(outDir, "extras.ts"),
  `${header}
// Bandeiras extras (territórios e afins) fora do MVP, preservadas para expansão futura.
import type { ExtraFlag } from "@/entities/country/country.types";

export const EXTRA_FLAGS: readonly ExtraFlag[] = ${JSON.stringify(extras.map(toExtraFlag), null, 2)};
`,
);

console.log(
  `Generated ${countries.length} countries, ${continents.length} continents, ${extras.length} extras.`,
);
